interface BloodMarker {
  name: string;
  unit: string;
  optimalRange?: string;
  description?: string;
}

export const bloodMarkers: Record<string, BloodMarker> = {
  vitaminD: {
    name: 'Vitamin D',
    unit: 'ng/mL',
    optimalRange: '50-80 ng/mL',
    description: 'Essential for bone health, immune function, and inflammation regulation',
  },
  ferritin: {
    name: 'Ferritin',
    unit: 'ng/mL',
    optimalRange: '100-200 ng/mL',
    description: 'Stores iron and releases it in a controlled fashion',
  },
  crp: {
    name: 'C-Reactive Protein (CRP)',
    unit: 'mg/L',
    optimalRange: '<1.0 mg/L',
    description: 'Marker of inflammation in the body',
  },
  hba1c: {
    name: 'Hemoglobin A1c',
    unit: '%',
    optimalRange: '<5.4%',
    description: 'Average blood sugar levels over the past 2-3 months',
  },
  tsh: {
    name: 'Thyroid Stimulating Hormone (TSH)',
    unit: 'mIU/L',
    optimalRange: '1.0-2.5 mIU/L',
    description: 'Regulates thyroid hormone production',
  },
  freeT3: {
    name: 'Free T3',
    unit: 'pg/mL',
    optimalRange: '3.0-4.2 pg/mL',
    description: 'Active thyroid hormone',
  },
  freeT4: {
    name: 'Free T4',
    unit: 'ng/dL',
    optimalRange: '1.3-1.8 ng/dL',
    description: 'Inactive thyroid hormone',
  },
  b12: {
    name: 'Vitamin B12',
    unit: 'pg/mL',
    optimalRange: '500-1000 pg/mL',
    description: 'Essential for nerve function and red blood cell production',
  },
  folate: {
    name: 'Folate',
    unit: 'ng/mL',
    optimalRange: '>15 ng/mL',
    description: 'Important for cell division and DNA synthesis',
  },
  magnesium: {
    name: 'Magnesium',
    unit: 'mg/dL',
    optimalRange: '2.2-2.6 mg/dL',
    description: 'Essential for muscle and nerve function, blood glucose control',
  },
  zinc: {
    name: 'Zinc',
    unit: 'mcg/dL',
    optimalRange: '90-110 mcg/dL',
    description: 'Important for immune function and wound healing',
  },
  homocysteine: {
    name: 'Homocysteine',
    unit: 'umol/L',
    optimalRange: '<8 umol/L',
    description: 'Amino acid linked to cardiovascular risk',
  },
  ldl: {
    name: 'LDL Cholesterol',
    unit: 'mg/dL',
    optimalRange: '<100 mg/dL',
    description: 'Low-density lipoprotein cholesterol',
  },
  hdl: {
    name: 'HDL Cholesterol',
    unit: 'mg/dL',
    optimalRange: '>60 mg/dL',
    description: 'High-density lipoprotein cholesterol',
  },
  triglycerides: {
    name: 'Triglycerides',
    unit: 'mg/dL',
    optimalRange: '<100 mg/dL',
    description: 'Type of fat in the blood',
  },
  apob: {
    name: 'Apolipoprotein B',
    unit: 'mg/dL',
    optimalRange: '<90 mg/dL',
    description: 'Better predictor of cardiovascular risk than LDL',
  },
  lpa: {
    name: 'Lipoprotein(a)',
    unit: 'nmol/L',
    optimalRange: '<75 nmol/L',
    description: 'Genetic risk factor for cardiovascular disease',
  },
  insulin: {
    name: 'Fasting Insulin',
    unit: 'uIU/mL',
    optimalRange: '2-6 uIU/mL',
    description: 'Hormone that regulates blood sugar',
  },
  fastingGlucose: {
    name: 'Fasting Glucose',
    unit: 'mg/dL',
    optimalRange: '75-90 mg/dL',
    description: 'Blood sugar level after fasting',
  },
  hscrp: {
    name: 'High-Sensitivity CRP',
    unit: 'mg/L',
    optimalRange: '<1.0 mg/L',
    description: 'More sensitive test for inflammation',
  },
  vitaminA: {
    name: 'Vitamin A',
    unit: 'mcg/dL',
    optimalRange: '38-98 mcg/dL',
    description: 'Important for vision, immune function, and reproduction',
  },
  vitaminE: {
    name: 'Vitamin E',
    unit: 'mg/L',
    optimalRange: '5-20 mg/L',
    description: 'Antioxidant that protects cells from damage',
  },
  vitaminK2: {
    name: 'Vitamin K2',
    unit: 'nmol/L',
    optimalRange: '>50 nmol/L',
    description: 'Important for bone and cardiovascular health',
  },
  selenium: {
    name: 'Selenium',
    unit: 'mcg/L',
    optimalRange: '120-160 mcg/L',
    description: 'Essential mineral with antioxidant properties',
  },
  copper: {
    name: 'Copper',
    unit: 'mcg/dL',
    optimalRange: '70-140 mcg/dL',
    description: 'Essential trace element for iron metabolism',
  },
  ceruloplasmin: {
    name: 'Ceruloplasmin',
    unit: 'mg/dL',
    optimalRange: '25-50 mg/dL',
    description: 'Copper transport protein',
  },
  zincCopperRatio: {
    name: 'Zinc/Copper Ratio',
    unit: 'ratio',
    optimalRange: '1.0-1.2',
    description: 'Important for immune function and inflammation',
  },
  rbcMagnesium: {
    name: 'RBC Magnesium',
    unit: 'mg/dL',
    optimalRange: '5.0-6.0 mg/dL',
    description: 'Better indicator of magnesium status than serum magnesium',
  },
  rbcZinc: {
    name: 'RBC Zinc',
    unit: 'mcg/dL',
    optimalRange: '12-14 mg/dL',
    description: 'Better indicator of zinc status than serum zinc',
  },
  rbcCopper: {
    name: 'RBC Copper',
    unit: 'mcg/dL',
    optimalRange: '90-130 mcg/dL',
    description: 'Better indicator of copper status than serum copper',
  },
  rbcSelenium: {
    name: 'RBC Selenium',
    unit: 'mcg/L',
    optimalRange: '180-400 mcg/L',
    description: 'Better indicator of selenium status than serum selenium',
  },
  rbcGlutathione: {
    name: 'RBC Glutathione',
    unit: 'umol/L',
    optimalRange: '1,000-1,500 umol/L',
    description: 'Master antioxidant of the cell',
  },
  rbcLipidPeroxides: {
    name: 'RBC Lipid Peroxides',
    unit: 'nmol/mL',
    optimalRange: '<4.0 nmol/mL',
    description: 'Marker of oxidative stress',
  },
  rbcSuperoxideDismutase: {
    name: 'RBC Superoxide Dismutase',
    unit: 'U/g Hb',
    optimalRange: '1,500-2,500 U/g Hb',
    description: 'Antioxidant enzyme',
  },
  rbcGlutathionePeroxidase: {
    name: 'RBC Glutathione Peroxidase',
    unit: 'U/g Hb',
    optimalRange: '25-50 U/g Hb',
    description: 'Antioxidant enzyme',
  },
  rbcCatalase: {
    name: 'RBC Catalase',
    unit: 'U/g Hb',
    optimalRange: '100-200 U/g Hb',
    description: 'Antioxidant enzyme',
  },
  rbcGlutathioneReductase: {
    name: 'RBC Glutathione Reductase',
    unit: 'U/g Hb',
    optimalRange: '4-8 U/g Hb',
    description: 'Antioxidant enzyme',
  },
  rbcGlutathioneSTransferase: {
    name: 'RBC Glutathione S-Transferase',
    unit: 'U/g Hb',
    optimalRange: '5-15 U/g Hb',
    description: 'Detoxification enzyme',
  },
  rbcGlucose6PhosphateDehydrogenase: {
    name: 'RBC G6PD',
    unit: 'U/g Hb',
    optimalRange: '8-16 U/g Hb',
    description: 'Enzyme important for red blood cell function',
  },
  rbcTransketolase: {
    name: 'RBC Transketolase',
    unit: 'U/g Hb',
    optimalRange: '0.8-1.3 U/g Hb',
    description: 'Marker of thiamine (B1) status',
  },
  rbcGlutamicOxaloaceticTransaminase: {
    name: 'RBC GOT',
    unit: 'U/g Hb',
    optimalRange: '5-15 U/g Hb',
    description: 'Marker of pyridoxine (B6) status',
  },
  rbcGlutamicPyruvicTransaminase: {
    name: 'RBC GPT',
    unit: 'U/g Hb',
    optimalRange: '5-15 U/g Hb',
    description: 'Marker of pyridoxine (B6) status',
  },
  rbcMethylmalonicAcid: {
    name: 'RBC Methylmalonic Acid',
    unit: 'nmol/L',
    optimalRange: '<100 nmol/L',
    description: 'Marker of vitamin B12 status',
  },
  rbcFolate: {
    name: 'RBC Folate',
    unit: 'ng/mL',
    optimalRange: '>280 ng/mL',
    description: 'Better indicator of folate status than serum folate',
  },
  rbcThiamine: {
    name: 'RBC Thiamine',
    unit: 'nmol/L',
    optimalRange: '100-150 nmol/L',
    description: 'Better indicator of thiamine status than serum thiamine',
  },
  rbcRiboflavin: {
    name: 'RBC Riboflavin',
    unit: 'nmol/L',
    optimalRange: '400-2,000 nmol/L',
    description: 'Better indicator of riboflavin status than serum riboflavin',
  },
  rbcPyridoxine: {
    name: 'RBC Pyridoxine',
    unit: 'nmol/L',
    optimalRange: '35-110 nmol/L',
    description: 'Better indicator of vitamin B6 status than serum B6',
  },
  rbcCobalamin: {
    name: 'RBC Cobalamin',
    unit: 'pmol/L',
    optimalRange: '1,000-2,000 pmol/L',
    description: 'Better indicator of vitamin B12 status than serum B12',
  },
  rbcBiotin: {
    name: 'RBC Biotin',
    unit: 'nmol/L',
    optimalRange: '0.8-2.0 nmol/L',
    description: 'Better indicator of biotin status than serum biotin',
  },
  rbcPantothenicAcid: {
    name: 'RBC Pantothenic Acid',
    unit: 'nmol/L',
    optimalRange: '1,000-2,000 nmol/L',
    description: 'Better indicator of pantothenic acid status than serum',
  },
  rbcVitaminC: {
    name: 'RBC Vitamin C',
    unit: 'mg/dL',
    optimalRange: '1.0-2.0 mg/dL',
    description: 'Better indicator of vitamin C status than serum vitamin C',
  },
  rbcVitaminE: {
    name: 'RBC Vitamin E',
    unit: 'mg/L',
    optimalRange: '5-20 mg/L',
    description: 'Better indicator of vitamin E status than serum vitamin E',
  },
  rbcBetaCarotene: {
    name: 'RBC Beta-Carotene',
    unit: 'mcg/dL',
    optimalRange: '10-85 mcg/dL',
    description: 'Better indicator of carotenoid status than serum',
  },
  rbcLycopene: {
    name: 'RBC Lycopene',
    unit: 'mcg/dL',
    optimalRange: '10-50 mcg/dL',
    description: 'Important carotenoid antioxidant',
  },
  rbcLuteinZeaxanthin: {
    name: 'RBC Lutein + Zeaxanthin',
    unit: 'mcg/dL',
    optimalRange: '5-30 mcg/dL',
    description: 'Important for eye health',
  },
  rbcCoenzymeQ10: {
    name: 'RBC CoQ10',
    unit: 'mcg/mL',
    optimalRange: '0.5-1.5 mcg/mL',
    description: 'Important for mitochondrial function',
  },
  rbcAlphaLipoicAcid: {
    name: 'RBC Alpha-Lipoic Acid',
    unit: 'ng/mL',
    optimalRange: '15-30 ng/mL',
    description: 'Powerful antioxidant',
  },
  rbcOmega3Index: {
    name: 'RBC Omega-3 Index',
    unit: '%',
    optimalRange: '8-12%',
    description: 'Marker of omega-3 fatty acid status',
  },
  rbcArachidonicAcid: {
    name: 'RBC Arachidonic Acid',
    unit: '%',
    optimalRange: '5-10%',
    description: 'Omega-6 fatty acid',
  },
  rbcEicosapentaenoicAcid: {
    name: 'RBC EPA',
    unit: '%',
    optimalRange: '>2%',
    description: 'Omega-3 fatty acid',
  },
  rbcDocosahexaenoicAcid: {
    name: 'RBC DHA',
    unit: '%',
    optimalRange: '>4%',
    description: 'Omega-3 fatty acid important for brain health',
  },
  rbcOleicAcid: {
    name: 'RBC Oleic Acid',
    unit: '%',
    optimalRange: '10-15%',
    description: 'Monounsaturated omega-9 fatty acid',
  },
  rbcLinoleicAcid: {
    name: 'RBC Linoleic Acid',
    unit: '%',
    optimalRange: '15-25%',
    description: 'Essential omega-6 fatty acid',
  },
  rbcAlphaLinolenicAcid: {
    name: 'RBC ALA',
    unit: '%',
    optimalRange: '0.2-0.6%',
    description: 'Essential omega-3 fatty acid',
  },
  rbcGammaLinolenicAcid: {
    name: 'RBC GLA',
    unit: '%',
    optimalRange: '0.1-0.3%',
    description: 'Omega-6 fatty acid',
  },
  rbcDihomoGammaLinolenicAcid: {
    name: 'RBC DGLA',
    unit: '%',
    optimalRange: '1.5-3.0%',
    description: 'Omega-6 fatty acid',
  },
  rbcDocosapentaenoicAcid: {
    name: 'RBC DPA',
    unit: '%',
    optimalRange: '0.5-1.5%',
    description: 'Omega-3 fatty acid',
  },
  rbcTransFattyAcids: {
    name: 'RBC Trans Fats',
    unit: '%',
    optimalRange: '<0.5%',
    description: 'Marker of processed food intake',
  },
  rbcOmega6Omega3Ratio: {
    name: 'RBC Omega-6:Omega-3 Ratio',
    unit: 'ratio',
    optimalRange: '1:1 to 4:1',
    description: 'Important balance for inflammation',
  },
  rbcArachidonicAcidEPA: {
    name: 'RBC AA:EPA Ratio',
    unit: 'ratio',
    optimalRange: '<5:1',
    description: 'Marker of inflammation balance',
  },
} as const;
