name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/gh-pages.yml'
      - 'scripts/build-static.sh'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying static content
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for proper versioning
          fetch-depth: 0
          # Don't persist credentials as we're not pushing back
          persist-credentials: false

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      # Build the static site
      - name: Build static site
        run: |
          cd frontend
          npm ci
          npm run build:static
          ls -la ../docs
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
      
      # Verify docs directory has content
      - name: Verify docs directory
        run: |
          if [ -z "$(ls -A docs)" ]; then
            echo "❌ Error: docs directory is empty after build"
            exit 1
          fi
          echo "✅ docs directory is valid"

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Upload the static site as an artifact
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          commit-message: "Deploy: Update site with timestamp ${{ env.BUILD_DATE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          build-script: |
            echo "BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          retention-days: 1
          
      # Set deployment environment URL for the next step
      - name: Set deployment URL
        run: echo "DEPLOY_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_ENV

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
